// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodeApl.API.Infrastructure.Data;

#nullable disable

namespace NodeApl.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241213124514_AddSamples")]
    partial class AddSamples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NodeApl.API.Domain.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Шаблоны",
                            Type = "Шаблон"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Шаблон 1",
                            ParentId = 1,
                            Type = "Шаблон"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Шаблон 2",
                            ParentId = 1,
                            Type = "Шаблон"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Шаблон 3",
                            ParentId = 1,
                            Type = "Шаблон"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Изделия",
                            Type = "Изделие"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Изделие 1",
                            ParentId = 2,
                            Type = "Изделие"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Изделие 2",
                            ParentId = 2,
                            Type = "Изделие"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Документы",
                            Type = "Документ"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Документ 1",
                            ParentId = 3,
                            Type = "Документ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Документ 2",
                            ParentId = 3,
                            Type = "Документ"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Документ 3",
                            ParentId = 3,
                            Type = "Документ"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Документ 4",
                            ParentId = 3,
                            Type = "Документ"
                        });
                });

            modelBuilder.Entity("NodeApl.API.Domain.Entities.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("Samples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 1",
                            NodeId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 1",
                            NodeId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 1",
                            NodeId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 1",
                            NodeId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 1",
                            NodeId = 4
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 2",
                            NodeId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 2",
                            NodeId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 2",
                            NodeId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 2",
                            NodeId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Шаблона 3",
                            NodeId = 6
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 1",
                            NodeId = 7
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 1",
                            NodeId = 7
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 1",
                            NodeId = 7
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 1",
                            NodeId = 7
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 1",
                            NodeId = 7
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 2",
                            NodeId = 8
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 2",
                            NodeId = 8
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Изделия 2",
                            NodeId = 8
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 1",
                            NodeId = 9
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 1",
                            NodeId = 9
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 2",
                            NodeId = 10
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 2",
                            NodeId = 10
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 3",
                            NodeId = 11
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 3",
                            NodeId = 11
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 4",
                            NodeId = 12
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Антон",
                            Name = "Описание Документа 4",
                            NodeId = 12
                        });
                });

            modelBuilder.Entity("NodeApl.API.Domain.Entities.Node", b =>
                {
                    b.HasOne("NodeApl.API.Domain.Entities.Node", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("NodeApl.API.Domain.Entities.Sample", b =>
                {
                    b.HasOne("NodeApl.API.Domain.Entities.Node", "Node")
                        .WithMany("Samples")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("NodeApl.API.Domain.Entities.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
